console.log("running!");

//original Array to store Question and answer list
var questArr =
['The first name of the mouse was x-y position indicator for a display system.',
'The first website was put online by NASA in 1991.',
'We now have to put the @ in an email address because of a typo.',
'The first item sold on eBay was a broken laser pointer.',
'The PDP-8, the first mini-computer, weighed more than 100 lb. (45 kg).',
'In 1952, the first IBM computer was intended for the Chase Manhattan Bank.',
'Silicon Valley is a suburb of Los Angeles.',
'Time magazine named “the computer” Person of the Year in 1982.',
'The transistor was invented at the beginning of the Second World War to allow communication between submarines.',
'The first website featured very detailed mathematical graphs.'];

var ansArr = ['t','f','f','t','t','f','f','t','f','f'];

var selectedQuest = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]; //Array that will contain the randomised sequence
var selectedAns = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]; //Array that will contain the randomised sequence
var totalQuest = questArr.length; // total no of Questions in this Quiz
var choice; //stores t or f
var currentQuest = 0; // Current Question number
var p1Score = 0; //Player1 Score
var p2Score = 0; //Player2 Score
var playerTurn = 1; // player1 = 1; player2 = 2


//Initialization of the game
questionGen(); // Generate Randomised question
displayQuestion(); // Output Question on screen
initButton(); // Activate all buttons
//console.log(selectedQuest); //debug
//console.log(selectedAns); //debug
//console.log(totalQuest); //debug

// main control of functions process
function main() {
    var nextButtonPtr = document.getElementById('nextButton');
    checkAnswer();

    if ( isGameOver() ) { // is the Quiz over? True - Game Over
        stopButton();
        nextButtonPtr.removeEventListener('click', nextQuest);
        nextButtonPtr.style.display = 'none'; // Hide "Next" button
        whoWon();
        alert('Press Restart button to continue');
    } //game over
}

// Generate random questions num and store sequence in the selectedQuest[] Array
function questionGen() {
    // Swops position of question no in selectedQuest;
    // j = stores the random num generated by Math;
    // x = pointer of source Question num
    // count = pointer of the target Question num

    var j, x, count;
    for (count = selectedQuest.length; count; count--) {
        j = Math.floor(Math.random() * count);
        x = selectedQuest[count - 1];
        selectedQuest[count - 1] = selectedQuest[j];
        selectedQuest[j] = x;
    }
    selectedAns = selectedQuest;
    //console.log(selectedQuest);
    //console.log(selectedAns);
}

//Initialize and activate the all buttons for Quiz
function initButton() {
    var restartButPtr = document.getElementById('restartButton'); //get ID for various buttons
    var trueButtonPtr = document.getElementById('trueButton');
    var falseButtonPtr = document.getElementById('falseButton');
    var nextButtonPtr = document.getElementById('nextButton');
    trueButtonPtr.addEventListener('click', getInput);
    falseButtonPtr.addEventListener('click', getInput);
    restartButPtr.addEventListener('click', restartButton);
    nextButtonPtr.addEventListener('click', nextQuest); // Fetch Next Question
    nextButtonPtr.style.display = 'none'; // Hide "Next" button
}

//Determine the button pressed, assign as input
function getInput(event) {
    var buttonID = event.target.id;
    var trueButtonPtr = document.getElementById('trueButton');
    var falseButtonPtr = document.getElementById('falseButton');
    //var button = document.getElementById(buttonID);

    if (buttonID === 'trueButton') choice = 't'; //Get true or false
    else choice = 'f';

    trueButtonPtr.style.display = 'none'; // after a true or false is choosen, hide "TRUE" & "FALSE" button
    falseButtonPtr.style.display = 'none';

    main(); // run the main program
}

//Check the choice again the correct answer
function checkAnswer() {
    //console.log('in checkAnswer');
    var checkAnswerPtr = document.getElementById('displayAnswer');
    var nextButtonPtr = document.getElementById('nextButton');

    if (choice == ansArr[selectedQuest[currentQuest]]) { //checks if the choice is the correct answer
        if (playerTurn === 1) p1Score++; // Answer is correct, add score to respective player
        else p2Score++;

        displayAnswer('The answer is Correct!!!'); // manually display message in the box
        checkAnswerPtr.style.background = 'yellow'; // Highlight box for a correct answer
        displayScore(); // display score
    } else {
        displayAnswer('The answer is Wrong!!!'); // manually display message in the box
        checkAnswerPtr.style.background = 'red'; // Highlight box for a correct answer
        checkAnswerPtr.style.color = 'white'; // Change text to White
        displayScore();
    }
    stopButton();  // deactivate TRUE and FALSE button
    nextButtonPtr.style.display = 'inline-block'; // unhide NEXT button
}

//It should return a true or false if the quiz is over.
function isGameOver() {
    //console.log('currentQuest :' + currentQuest + ' totalQuest :' + totalQuest);
    if (currentQuest === (totalQuest - 1)) return true;
    else return false;
}

// Display next Question. Waits for NEXT button to be clicked
function nextQuest(event) {
    var holdID = event.target.id;
    var checkAnswerPtr = document.getElementById('displayAnswer');
    var trueButtonPtr = document.getElementById('trueButton');
    var falseButtonPtr = document.getElementById('falseButton');

    checkAnswerPtr.style.background = '#F4F0BB'; // Back to original color
    checkAnswerPtr.style.color = 'black';

    displayAnswer('Select True or False');// manual Text display
    currentQuest++; // Point to the next question
    playTurn(); // toggle between Player 1/2
    displayQuestion();
    //console.log('In nextQuest, Current Question :' + currentQuest);
    initButton(); // activate TRUE/FALSE button again
    trueButtonPtr.style.display = 'inline-block'; // Unhide TRUE/FALSE button
    falseButtonPtr.style.display = 'inline-block';
}

// toggle between Player 1 and 2
function playTurn() {
    var playerStatusPtr = document.getElementById('playerStatus');
    if (playerTurn === 1) {
        playerTurn = 2;
        playerStatusPtr.style.background = '#febbbb';// Change color of Box for Respective Player
    } else {
        playerTurn = 1;
        playerStatusPtr.style.background = '#b2e1ff';
    }
    //console.log('in playTurn player ' + playerTurn);
}

// Deactivate TRUE and FALSE Button
function stopButton() {
    var trueButtonPtr = document.getElementById('trueButton');
    var falseButtonPtr = document.getElementById('falseButton');

    trueButtonPtr.removeEventListener('click', getInput);
    falseButtonPtr.removeEventListener('click', getInput);
}

//Display player with the higher score as winner
function whoWon() {
    if (p1Score > p2Score) {
        displayAnswer('Game Completed. Winner is Player 1!');
    } else
        displayAnswer('Game Completed. Winner is Player 2!');
}

// Display question in the Display Box ID = displayQuest
function displayQuestion() {
    var playerStatusPtr = document.getElementById('playerStatus');
    var questdisplayPtr = document.getElementById('displayQuest');
    var questTextdisplayPtr = document.getElementById('displayQuestText');
    console.log('in displayQuestion playTurn' + playerTurn);
    playerStatusPtr.innerHTML = 'Player ' + playerTurn;
    questdisplayPtr.innerHTML = 'Question ' + (currentQuest + 1) + ': ';
    questTextdisplayPtr.innerHTML = questArr[selectedQuest[currentQuest]];
}

// Display any text on the displayAnswer Box
function displayAnswer(answer) {
    var answerPtr = document.getElementById('displayAnswer');
    answerPtr.innerHTML = answer;
}

// Update score to the score board
function displayScore() {
    var score1Ptr = document.getElementById('p1ScoreBox');
    var score2Ptr = document.getElementById('p2ScoreBox');
    score1Ptr.innerHTML = 'Player 1 Score is ' + p1Score + '.';
    score2Ptr.innerHTML = 'Player 2 Score is ' + p2Score + '.';
}

//Restart a new game. Waits for Restart Button to be pressed.
function restartButton(event) {
    var restartID = event.target.id;
    var trueButtonPtr = document.getElementById('trueButton');
    var falseButtonPtr = document.getElementById('falseButton');

    //console.log('in Reset button');
    selectedQuest = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]; //Reset variables to default
    totalQuest = questArr.length;;
    currentQuest = 0;
    p1Score = 0;
    p2Score = 0;
    playerTurn = 1;

    questionGen();
    displayQuestion();
    displayAnswer('Answer True or False');
    displayScore();
    trueButtonPtr.style.display = 'inline-block';
    falseButtonPtr.style.display = 'inline-block';

    initButton();
}
